apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: lianyz
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from tthe Kubernetes clusterIP
          restartPolicy: OnFailure