apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container1
    image: busybox
    command: [ 'sh', '-c', 'echo Hello Kubernetes 1! && sleep 3600']