apiVersion: apps/v1
kind: Deployment
metadata:
  name: patch-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patch-demo
  template:
    metadata:
      labels:
        app: patch-demo
    spec:
      containers:
        - name: myapp-container1
          image: busybox
          command: [ 'sh', '-c', 'echo Hello Kubernetes 1! && sleep 3600']