apiVersion: v1
kind: Deployment
metadata:
  name: patch-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patch-demo
  template:
    metadata:
      labels:
        app: patch-demo
    spec:
      containers:
        - name: myapp-container2
          image: busybox
          command: [ 'sh', '-c', 'echo Hello Kubernetes 2! && sleep 3600']