apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: lianyz
spec:
  containers:
  - name: mysql-client
    image: mysql:5.7
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "30d"]