apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv3
  namespace: lianyz
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.34.2
    path: "/www3"