apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-role
  namespace: lianyz
rules:
- apiGroups: [""]
  resources: ["pods"]
  resourceNames: [""] # 针对某个具体对象设置权限
  verbs: ["get", "watch", "list"]