apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-rolebinding-sa
  namespace: lianyz
subjects:
- kind: ServiceAccount
  name: example-sa
  namespace: lianyz
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io