apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: lianyz
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test
      mountPath: /data
    - name: test2
      mountPath: /data2
  volumes:
  - name: test
    flexVolume:
      driver: "k8s/nfs"
      fsType: "nfs"
      options:
        server: 192.168.34.2
        share: "/www"
  - name: test2
    persistentVolumeClaim:
      claimName: pvc-flex-nfs  